feature/TM-38/roles
nikitahessde/nextjs-task-manager pull request #6
Opened 2024-10-24 08:07 UTC by nikitahessde

2024-10-24 16:13 UTC, jevgenijs-jaunslavietis requested changes
Business requirements for different roles are not implemented.

2024-10-24 16:13 UTC, jevgenijs-jaunslavietis commented on .idea/inspectionProfiles/Project_Default.xml
Please move .idea folder to gitignore and remove from git

2024-10-24 16:13 UTC, jevgenijs-jaunslavietis commented on context/user-context.tsx
Please re-work users in NextJs way. We don't need to fetch all users every time we load application. They are needed only in certain places. Context is not needed at all there.

2024-10-24 16:13 UTC, jevgenijs-jaunslavietis commented on lib/auth.ts
> +  secret: process.env.NEXTAUTH_SECRET,
Add .env.example file with all environment variable keys

2024-10-24 16:13 UTC, jevgenijs-jaunslavietis commented on models/User.ts
How do you ensure that user password is not exposed to frontend?

2024-10-24 17:08 UTC, nikitahessde commented on models/User.ts
I always hash passwords before storing them in the database

2024-10-24 17:09 UTC, nikitahessde commented on models/User.ts
![Screenshot 2024-10-24 at 20 08 43](https://github.com/user-attachments/assets/c9e25568-df4a-47f6-81cb-fef5c08ce2c4)

2024-10-25 09:15 UTC, jevgenijs-jaunslavietis commented on models/User.ts
It is fine to store password like that in database. Still, we should not return passwords (even hashed) through APIs

2024-10-25 09:30 UTC, jevgenijs-jaunslavietis commented on components/user-details.tsx
> +export const UserDetails = () => {
Let's do one more iteration towards NextJs application :) 
There are a way too many states for "almost static" page. For example, list of users can be pre-fetched on server side. useEffect is not needed at all. Session should be handled on the backend as currently there is no API protection which mean that I can update user without admin rights.
updateUser can be server action where you can call db directly.
Same applies to user list.
Also, it is preferred to have some split between higher order components (HOC) and UI components (dumb components). Please have a look into this pattern and update code accordingly.

2024-10-25 13:07 UTC, jevgenijs-jaunslavietis commented on components/user-details.tsx
> +    await editUser(user.email, { name: updatedUser?.name, role: updatedUser?.role }, session);
session should not be passed like that from frontend. It is usually in httpOnly cookie

2024-10-25 13:07 UTC, jevgenijs-jaunslavietis commented on components/user-details.tsx
> +  const handleChange = (email: string, field: keyof User, value: string) => {
Is there a way to cancel user editing and revert changes?

2024-10-25 13:07 UTC, jevgenijs-jaunslavietis commented on app/signup/page.tsx
>    const onSubmit = async (data: any) => {
should not be of type `any`

2024-10-25 13:07 UTC, jevgenijs-jaunslavietis commented on components/user-details.tsx
> +  const [editedUsers, setEditedUsers] = useState<User[]>(users);
Why do you need the list of all users on user details page?

2024-10-29 10:22 UTC, jevgenijs-jaunslavietis approved these changes

2024-10-29 10:22 UTC, jevgenijs-jaunslavietis commented on components/create-task.tsx
> +  console.log(session);
clean up console.log

2024-10-29 10:22 UTC, jevgenijs-jaunslavietis commented on app/signup/page.tsx
> +type FormData = {
Name should be a bit more precise like `RegistrationFormData`

2024-10-29 10:24 UTC, jevgenijs-jaunslavietis commented on app/user-details/page.tsx
> +  const editUser = async (email: string, updates: Partial<{ name: string }>) => {
should validate if user is allowed to edit users

2024-10-29 10:32 UTC, jevgenijs-jaunslavietis requested changes
Where is implementation for business rules? Backend validation of roles is mandatory

Admin (can create tasks, edit tasks, delete tasks and view all users and their details)

Manager (Can ONLY assign users to a specific task)

User (ability to just view the details and task list)

2024-10-29 10:32 UTC, jevgenijs-jaunslavietis commented on models/User.ts
> +    role: {
actually, this should be an array of roles

2024-10-29 16:23 UTC, jevgenijs-jaunslavietis requested changes

2024-10-29 16:23 UTC, jevgenijs-jaunslavietis commented on actions/register.ts
> +  role: string[];
should be roles there and everywhere else if it is array of roles

2024-10-29 16:23 UTC, jevgenijs-jaunslavietis commented on actions/register.ts
> +  role: string[];
it is better to create a type or enum of exact roles to have more type-safety

2024-10-29 16:23 UTC, jevgenijs-jaunslavietis commented on app/api/tasks/[id]/route.ts
> +  if (!session || !(session.user.role[0] === "admin" || session.user.role[0] === "manager")) {
Need to check if array of `roles` contains role `admin` or `manager`

2024-10-29 16:23 UTC, jevgenijs-jaunslavietis commented on app/api/tasks/[id]/route.ts
> +  if (!session || !(session.user.role[0] === "admin")) {
same as above

2024-10-29 16:23 UTC, jevgenijs-jaunslavietis commented on app/api/tasks/route.ts
> +  if (!session || !(session.user.role[0] === "admin")) {
same

2024-10-29 16:23 UTC, jevgenijs-jaunslavietis commented on app/user-details/page.tsx
> +    await User.updateOne({ email }, updates);
So, I can still edit it with role `user`

2024-10-31 11:58 UTC, jevgenijs-jaunslavietis requested changes

2024-10-31 11:58 UTC, jevgenijs-jaunslavietis commented on actions/register.ts
> +  role: UserRole[];
according to naming convention it should be role**s**

2024-10-31 11:58 UTC, jevgenijs-jaunslavietis commented on actions/register.ts
> +  role: UserRole[];
here and everywhere in the project where you are using arrays

2024-10-31 11:58 UTC, jevgenijs-jaunslavietis commented on components/user-details.tsx
> +              value={user.role[0]}
it should support array of roles

2024-10-31 11:58 UTC, jevgenijs-jaunslavietis commented on components/user-list.tsx
> +              <p>{user.role[0]}</p>
All roles should be displayed

2024-11-01 08:01 UTC, jevgenijs-jaunslavietis requested changes

2024-11-01 08:01 UTC, jevgenijs-jaunslavietis commented on components/create-task.tsx
> +      <Snackbar
Since this is snackbar, I suggest to put it somewhere at the top of application and create a context. In this case, you won't have to put snackbar in every component

2024-11-01 08:01 UTC, jevgenijs-jaunslavietis commented on models/User.ts
> +export enum UserRoles {
This should be in singular form :)

2024-11-01 08:01 UTC, jevgenijs-jaunslavietis commented on components/create-task.tsx
> +  role: UserRoles[];
?

2024-11-01 09:59 UTC, jevgenijs-jaunslavietis approved these changes

2024-11-01 10:00 UTC, merged